export const profiles = [
  {
    id: "sari",
    name: "Sari K.",
    avatar: "👩",
    avatarBg: "#fde8dc",
    dist: "0.4 km",
    type: "Perhe · 2 lasta",
    text: "Etsimme leikkikaveria 4-vuotiaalle Ellille. Käymme usein Kotipolun leikkipuistossa iltapäivisin!",
    tags: [
      { label: "Leikkikaverit", variant: "terra" as const },
      { label: "4-vuotiaat", variant: "sage" as const },
      { label: "Leikkipuisto", variant: "sand" as const },
    ],
    time: "Aktiivinen tänään",
  },
  {
    id: "mikko",
    name: "Mikko L.",
    avatar: "👨",
    avatarBg: "#e8ecf5",
    dist: "0.8 km",
    type: "Perhe · 3 lasta",
    text: "Meillä on iso piha ja trampoliini. Tervetuloa leikkimään! Lapset 3, 6 ja 8 vuotta. Viikonloput parhaita.",
    tags: [
      { label: "Leikkikaverit", variant: "terra" as const },
      { label: "Piha", variant: "sage" as const },
      { label: "Viikonloput", variant: "sand" as const },
    ],
    time: "Eilen",
  },
  {
    id: "erkki",
    name: "Erkki V.",
    avatar: "👴",
    avatarBg: "#e8f0e8",
    dist: "1.2 km",
    type: "Eläkeläinen",
    text: "Tarjoan apua pieniin kotitöihin, lumitöihin ja kauppa-asioihin. Minulla on aikaa ja hyvä fyysinen kunto.",
    tags: [
      { label: "Apua tarjolla", variant: "sage" as const },
      { label: "Lumityöt", variant: "sand" as const },
      { label: "Kauppa-asiat", variant: "sand" as const },
    ],
    time: "Aktiivinen tänään",
  },
  {
    id: "anna",
    name: "Anna M.",
    avatar: "👩‍🦱",
    avatarBg: "#fdf0e0",
    dist: "1.5 km",
    type: "Perhe · 1 lapsi",
    text: "Uusi alueella! Etsimme uusia tuttavuuksia. Poikamme on 2v ja rakastaa autoja ja hiekkalaatikkoa.",
    tags: [
      { label: "Leikkikaverit", variant: "terra" as const },
      { label: "2-vuotiaat", variant: "sage" as const },
      { label: "Uusi alueella", variant: "terra" as const },
    ],
    time: "2 päivää sitten",
  },
  {
    id: "liisa",
    name: "Liisa H.",
    avatar: "👩",
    avatarBg: "#f0e8f5",
    dist: "2.1 km",
    type: "Harrastaja",
    text: "Järjestän pientä kävelyporukkaa joka keskiviikko klo 9. Kaikki tervetuloa — rauhallinen tahti, kahvit perään!",
    tags: [
      { label: "Kävely", variant: "sage" as const },
      { label: "Aamuisin", variant: "sand" as const },
      { label: "Kaikki ikäluokat", variant: "sand" as const },
    ],
    time: "Aktiivinen tänään",
  },
  {
    id: "jukka",
    name: "Jukka P.",
    avatar: "🧑",
    avatarBg: "#e8f5f0",
    dist: "2.8 km",
    type: "Harrastaja · Lemmikki",
    text: "Meillä on ystävällinen labradorinnoutaja Haukku. Etsimme kävelyseuraa ja leikkikaveria koiralle!",
    tags: [
      { label: "Lemmikki", variant: "terra" as const },
      { label: "Koirakaverit", variant: "sage" as const },
      { label: "Ulkoilu", variant: "sand" as const },
    ],
    time: "3 päivää sitten",
  },
]

export const events = [
  {
    id: "e1",
    day: "26",
    month: "Hel",
    name: "Kävelykerho — Kotipolku",
    loc: "Kotipolun leikkipuisto · klo 9:00",
    participants: 8,
    badges: ["Ilmainen", "Auki kaikille"],
  },
  {
    id: "e2",
    day: "1",
    month: "Mar",
    name: "Lasten talvipäivä · Sveitsinpuisto",
    loc: "Sveitsinpuisto · klo 13:00",
    participants: 14,
    badges: ["Ilmainen", "Perheille"],
  },
  {
    id: "e3",
    day: "5",
    month: "Mar",
    name: "Naapurikahvit — Villähde",
    loc: "Villähteen seurantalo · klo 14:00",
    participants: 6,
    badges: ["Ilmainen", "Auki kaikille"],
  },
  {
    id: "e4",
    day: "8",
    month: "Mar",
    name: "Kirjastokerho lapsille",
    loc: "Hyvinkään kirjasto · klo 10:30",
    participants: 12,
    badges: ["Ilmainen", "3–7v"],
  },
  {
    id: "e5",
    day: "12",
    month: "Mar",
    name: "Talkoot — Yhteinen puutarha",
    loc: "Kaukasten yhteispiha · klo 11:00",
    participants: 9,
    badges: ["Ilmainen", "Kaikki tervetuloa"],
  },
]

export const helpRequests = [
  {
    id: "h1",
    title: "🌨️ Lumilapiointi — piha ja portaat",
    urgent: true,
    desc: "Selkäni on kipeä enkä pysty lapioimaan. Pieni piha, kestää noin 30 min. Tarjoan kahvit ja pullaa avuksi tulleelle!",
    author: "Ritva H.",
    authorIcon: "👩‍🦳",
    dist: "0.6 km",
    time: "Tänään 08:30",
  },
  {
    id: "h2",
    title: "🛒 Kauppa-apu — Prisma",
    urgent: false,
    desc: "Menisin Prismaan lauantaina n. klo 11. Voisiko joku ottaa kyytiin? Asun Kotipolun alussa. Korvaan bensarahat.",
    author: "Veikko M.",
    authorIcon: "👴",
    dist: "1.4 km",
    time: "Eilen 16:20",
  },
  {
    id: "h3",
    title: "🐕 Koiran ulkoilutus · 3 päivää",
    urgent: false,
    desc: "Matkustamme seuraavat 3 päivää. Tarvitaan ulkoiluttaja Nipsun kanssa, 2x/pv. Nips on iloinen beagle, 4v.",
    author: "Taina & Riku",
    authorIcon: "👩",
    dist: "2.2 km",
    time: "2 päivää sitten",
  },
  {
    id: "h4",
    title: "🔧 IKEA-hyllyn kasaus",
    urgent: false,
    desc: "Tarvitsen kädet kasaamaan suuren Kallax-hyllyn. Omat työkalut löytyy. Illalla tai viikonloppuna sopii. Tarjoan pizzan!",
    author: "Petri L.",
    authorIcon: "🧑",
    dist: "3.1 km",
    time: "3 päivää sitten",
  },
  {
    id: "h5",
    title: "🌱 Harjaantuva puutarhuri tarjolla",
    urgent: false,
    desc: "Olen eläkkeellä ja rakastan puutarhanhoitoa. Tarjoan apua keväisin ja syksyisin pihatöissä. Täysin ilmainen!",
    author: "Erkki V.",
    authorIcon: "👴",
    dist: "1.2 km",
    time: "Tänään",
  },
]

export const messages = [
  {
    id: "m1",
    name: "Sari K.",
    avatar: "👩",
    avatarBg: "#fde8dc",
    preview: "Hei! Voitaisiinko tulla huomen...",
    time: "10:24",
    unread: true,
  },
  {
    id: "m2",
    name: "Erkki V.",
    avatar: "👴",
    avatarBg: "#e8f0e8",
    preview: "Olen vapaana perjantaina jos t...",
    time: "Eilen",
    unread: true,
  },
  {
    id: "m3",
    name: "Mikko L.",
    avatar: "👨",
    avatarBg: "#e8ecf5",
    preview: "Tervetuloa! Meillä on tilaa...",
    time: "Ma",
    unread: false,
  },
]

export const activity = [
  {
    icon: "👩",
    iconBg: "#fde8dc",
    text: "Sari K.",
    desc: "lisäsi profiilin lähialueellesi",
    time: "Tänään 10:24",
  },
  {
    icon: "👴",
    iconBg: "#e8f0e8",
    text: "Erkki V.",
    desc: "tarjoutui auttamaan lumitöissä",
    time: "Tänään 08:15",
  },
  {
    icon: "📅",
    iconBg: "#e8f5f0",
    text: "Uusi tapahtuma:",
    desc: "Kävelykerho ke 26.2.",
    time: "Eilen 16:40",
  },
  {
    icon: "👩‍🦱",
    iconBg: "#fdf0e0",
    text: "Anna M.",
    desc: "muutti alueelle — toivota tervetulleeksi!",
    time: "2 päivää sitten",
  },
]

export const mapPins = [
  { left: "33%", top: "36%", label: "👩 Sari K. · 0.4km", variant: "terra" as const },
  { left: "48%", top: "55%", label: "👨 Mikko L. · 0.8km", variant: "terra" as const },
  { left: "55%", top: "38%", label: "👴 Erkki V. · apua", variant: "sage" as const },
  { left: "28%", top: "62%", label: "👩‍🦱 Anna M. · 1.5km", variant: "terra" as const },
  { left: "65%", top: "28%", label: "📅 Kävelykerho", variant: "sage" as const },
  { left: "70%", top: "60%", label: "🐕 Jukka P. · 2.8km", variant: "terra" as const },
]

export const browseFilters = ["Kaikki", "🧒 Leikkikaverit", "🤝 Apua tarjolla", "🌱 Harrastukset", "👴 Seniorit", "🐕 Lemmikkejä"]
export const eventFilters = ["Kaikki", "🧒 Lapsille", "🚶 Liikunta", "🎨 Kulttuuri", "☕ Kokoontuminen"]
export const helpFilters = ["Kaikki", "🏠 Kotityöt", "🛒 Kauppa-asiat", "🚗 Kyyditys", "🔧 Korjaukset", "🐕 Lemmikkihoito"]
