'use client'
import {useCallback,useEffect,useState} from 'react'
type D={time:string;departure_ts:number;delay_min:number;headsign:string;route_short:string;mode:string}
type S={gtfs_id:string;name:string;distance:string;departures:D[]}
const modes:Record<string,string>={BUS:'🚌',TRAM:'🚊',RAIL:'🚂',SUBWAY:'🚇',FERRY:'⛴️'}
const radii=[.3,.5,1,2,5]
export function TransitView(){
 const[radius,setRadius]=useState(.5),[stops,setStops]=useState<S[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/transit/nearby-stops?radius_km='+radius,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setStops(d.stops??[])}catch(e){setError(e instanceof Error?e.message:'Aikataulujen haku epäonnistui.')}finally{setLoading(false)}},[radius])
 useEffect(()=>{void load()},[load])
 return <section className="mx-auto w-full max-w-5xl p-4 sm:p-6 lg:p-8">
  <div className="mb-5"><p className="text-sm font-semibold text-terracotta">Lähellä</p><h1 className="font-serif text-3xl font-semibold text-lahella-text">Lähiliikenne</h1><p className="mt-2 text-sm text-lahella-text2">Bussit ja junat lähellä sijaintiasi.</p></div>
  <div className="mb-5 flex gap-2 overflow-x-auto pb-1">{radii.map(v=><button key={v} onClick={()=>setRadius(v)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-semibold ${radius===v?'bg-terracotta text-white':'bg-card text-lahella-text2 ring-1 ring-border'}`}>{v<1?v*1000+' m':v+' km'}</button>)}</div>
  {error&&<div className="mb-4 rounded-2xl bg-amber-50 px-4 py-3 text-sm text-amber-800">{error}</div>}
  {loading?<div className="rounded-2xl border border-border bg-card p-12 text-center text-sm text-lahella-muted">Haetaan lähiliikennettä…</div>:stops.length===0?<div className="rounded-2xl border border-border bg-card p-12 text-center"><div className="text-4xl">🚏</div><h2 className="mt-3 font-serif text-xl font-semibold">Ei pysäkkejä lähellä</h2><p className="mt-2 text-sm text-lahella-text2">Tarkista profiilisi sijainti tai kokeile suurempaa hakusädettä.</p></div>:<div className="space-y-3">{stops.map(s=><article key={s.gtfs_id} className="rounded-2xl border border-border bg-card p-4 sm:p-5"><div className="mb-3 flex items-center justify-between gap-3 border-b border-border pb-3"><h2 className="truncate font-semibold">{'🚏 '+s.name}</h2><span className="shrink-0 rounded-full bg-terracotta-faint px-2.5 py-1 text-xs font-bold text-terracotta">{s.distance}</span></div><div>{s.departures.map((d,i)=>{const mins=Math.max(0,Math.floor((d.departure_ts-Date.now()/1000)/60));return <div key={i} className="grid grid-cols-[auto_auto_1fr_auto] items-center gap-2 py-1.5"><span>{modes[d.mode]??'🚌'}</span><span className="rounded-md bg-terracotta px-2 py-0.5 text-xs font-bold text-white">{d.route_short||'—'}</span><span className="truncate text-sm text-lahella-text2">→ {d.headsign||'Määränpää ei tiedossa'}</span><span className={`text-sm font-bold ${mins<=5?'text-terracotta':''}`}>{mins<=0?'nyt':mins<60?mins+' min':d.time}</span>{d.delay_min>0&&<span className="col-span-full text-right text-xs font-semibold text-red-600">+{d.delay_min} min</span>}</div>})}</div></article>)}</div>}
 </section>
}